using System;
using System.Text.Json.Serialization;

namespace Sufficit.Gateway.Zabbix
{
    /// <summary>
    /// Telephone destination that belongs to a Zabbix gateway integration.
    /// Enabled destinations are ordered by <see cref="Priority"/> when an alert route is executed.
    /// </summary>
    public class ZabbixGatewayDestination
    {
        /// <summary>
        /// Unique identifier of the destination row.
        /// A new identifier is generated by the persistence provider when this value is empty.
        /// </summary>
        [JsonPropertyName("id")]
        public Guid Id { get; set; }

        /// <summary>
        /// Identifier of the parent <see cref="ZabbixGatewayIntegration"/>.
        /// The destinations endpoint assigns this value from its route parameter instead of trusting client input.
        /// </summary>
        [JsonPropertyName("integrationid")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public Guid IntegrationId { get; set; }

        /// <summary>
        /// Tenant context that owns the destination.
        /// It is copied from the parent integration when destinations are persisted.
        /// </summary>
        [JsonPropertyName("contextid")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public Guid ContextId { get; set; }

        /// <summary>
        /// Human-readable person, team or duty label shown in configuration and alert history.
        /// </summary>
        [JsonPropertyName("title")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull | JsonIgnoreCondition.WhenWritingDefault)]
        public string? Title { get; set; }

        /// <summary>
        /// Telephone number dialed for this destination.
        /// Prefer an E.164-formatted value so routing remains unambiguous across regions.
        /// </summary>
        [JsonPropertyName("phone_number")]
        public string PhoneNumber { get; set; } = string.Empty;

        /// <summary>
        /// Escalation order of the destination; lower values are attempted first.
        /// Values below 1 are normalized to 1 by the persistence provider.
        /// </summary>
        [JsonPropertyName("priority")]
        public int Priority { get; set; } = 1;

        /// <summary>
        /// Determines whether the destination participates in new telephone alert executions.
        /// Disabled rows remain saved so they can be re-enabled without re-entering their data.
        /// </summary>
        [JsonPropertyName("enabled")]
        public bool Enabled { get; set; } = true;

        /// <summary>
        /// Database-managed timestamp of the most recent persisted row update.
        /// Clients should treat this value as read-only concurrency and audit metadata.
        /// </summary>
        [JsonPropertyName("timestamp")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public DateTime Timestamp { get; set; }
    }
}
